requirepass <%= p('auth.password') %>
protected-mode no

<% if p('persistent') -%>
appendonly yes
# we should already be *in* the store dir
appendfilename "valkey.aof"
appendfsync everysec

<% if p('valkey.no-appendfsync-on-rewrite') -%>
no-appendfsync-on-rewrite <%= p('valkey.no-appendfsync-on-rewrite') ? "yes" : "no" %>
<% end %>
<% if p('valkey.auto-aof-rewrite-percentage') -%>
auto-aof-rewrite-percentage <%= p('valkey.auto-aof-rewrite-percentage') %>
<% end %>
<% if p('valkey.auto-aof-rewrite-min-size') -%>
auto-aof-rewrite-min-size <%= p('valkey.auto-aof-rewrite-min-size') %>
<% end %>
<% end %>

<% if not p('lua.scripting-enabled') -%>
rename-command EVAL ""
rename-command EVALSHA ""
<% else %>
# lua scripting enabled
<% end %>

maxmemory-policy "<%= p('valkey.maxmemory-policy') %>"
maxmemory <%= p('valkey.maxmemory') %>

notify-keyspace-events "<%= p('valkey.notify-keyspace-events') %>"
slowlog-log-slower-than <%= p('valkey.slowlog-log-slower-than') %>
slowlog-max-len <%= p('valkey.slowlog-max-len') %>

timeout <%= p('client.timeout') %>
tcp-keepalive <%= p('client.tcpkeepalive') %>
maxclients  <%= p('client.connections') %>

<% p('valkey.disabled-commands').each do |cmd| -%>
rename-command <%= cmd %> ""
<% end %>

<% if p('valkey.tls.enabled') -%>
port <%= p('valkey.tls.dual-mode') ? 6379 : 0 %>
tls-port <%= p('valkey.tls.dual-mode') ? 16379 : 6379 %>
tls-cert-file /var/vcap/jobs/standalone-9/config/tls/valkey.cert
tls-key-file /var/vcap/jobs/standalone-9/config/tls/valkey.key
tls-ca-cert-file /var/vcap/jobs/standalone-9/config/tls/valkey.ca
tls-auth-clients no
tls-protocols "TLSv1.2 TLSv1.3"
<% else %>
port 6379
<% end %>
